name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: tree-sitter-gpr
    steps:
      - name: Checkout (tree-sitter-gpr)
        uses: actions/checkout@v4
        with:
          path: tree-sitter-gpr

      - name: Checkout (gpr)
        uses: actions/checkout@v4
        with:
          repository: adacore/gpr
          path: gpr

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Module Dependencies
        run: npm install

      - name: Test Project (Corpus)
        run: npm run test

      # Initialize tree-sitter config to prevent nuisance message
      # during tree-sitter parsing, when config doesn't exist.
      - name: Create Tree-sitter Config
        run: npx tree-sitter init-config

      - name: Test Project (GPR)
        run: npm run gpr-test
